apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-orderform
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-orderform
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-orderform
    spec:
      imagePullSecrets:
      - name: prodpipelinevariables
      containers:
      - name: gpitfutures-bc-app-orderform
        image: gpitfuturesprodacr.azurecr.io/nhsd/buying-catalogue/order-form:20200520.15 
        ports:
        - containerPort: 3006
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
        env:
        - name: BASE_URL
          value: "/order"
        - name: PUBLIC_BROWSE_BASE_URL
          value: "https://buyingcatalogue.digital.nhs.uk"
        - name: APP_BASE_URI
          value: "https://buyingcatalogue.digital.nhs.uk"
        - name: ORDER_API_URL 
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: ORDER_API_URL 
        - name: LOGGER_LEVEL
          value: "info"
        - name: OIDC_BASE_URI
          value: "https://buyingcatalogue.digital.nhs.uk/identity"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: OIDC_CLIENT_SECRET
        - name: MAX_COOKIE_AGE
          value: "3600000"
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: COOKIE_SECRET
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: REDIS_HOST
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_TLS
          value: "true"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: REDIS_PASS
        - name: IDENTITY_SERVER
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: IDENTITY_SERVER
---
apiVersion: v1
kind: Service
metadata:
  name: orderform
spec:
  ports:
  - port: 3006
  selector:
    app: gpitfutures-bc-app-orderform
