apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-bapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-bapi
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-bapi
    spec:
      containers:
      - name: gpitfutures-bc-app-bapi
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/bapi
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 1
        env:
        - name: ConnectionStrings__BuyingCatalogue
          value: srt-connectionstringsbuyingcatalogue@azurekeyvault
        - name: APICLIENTSETTINGS__DOCUMENTAPI__BASEURL
          value: srt-apiclientsettingdocumentapibaseurl@azurekeyvault
---
apiVersion: v1
kind: Service
metadata:
 name: api
spec:
  ports:
  - port: 5100
    targetPort: 80
    protocol: TCP
  selector:
    app: gpitfutures-bc-app-bapi
