apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-api
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-api
    spec:
      imagePullSecrets:
      - name: pprodpipelinevariables
      containers:
      - name: gpitfutures-bc-app-api
        image: gpitfuturespprodacr.azurecr.io/nhsd/buying-catalogue/api
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: ConnectionStrings__BuyingCatalogue
          valueFrom:
            secretKeyRef:
              name: pprodpipelinevariables
              key: ConnectionStrings__BuyingCatalogue
        - name: APICLIENTSETTINGS__DOCUMENTAPI__BASEURL
          valueFrom:
            secretKeyRef:
              name: pprodpipelinevariables
              key: APICLIENTSETTINGS__DOCUMENTAPI__BASEURL
