{{- $azureblobUrl:=  printf "http://%s.%s" (include "azurite.fullname" . ) .Release.Namespace }}
{{- $dapiUrl:= ternary (cat (include "call-nested" (list . "dapi" "dapi.fullname")) "." .Release.Namespace) "localhost" .Values.dapi.enabled -}}
{{- $bapiUrl:= ternary (cat (include "call-nested" (list . "bapi" "bapi.fullname")) "." .Release.Namespace) "localhost" .Values.bapi.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "local-env.fullname" . }}
  labels:     
    {{- include "local-env.labels" . | nindent 4 }}
data:
  dapi-url: {{ printf "http://%s:%d" $dapiUrl (.Values.dapi.service.port | int ) }}
  bapi-url: {{ printf "http://%s:%d" $bapiUrl (.Values.bapi.service.port | int ) }}