{{- $bapiDbValues:= index .Values "bapi-db" -}} #work around for chart naming convention clash - https://github.com/helm/helm/issues/2192
{{- $saPassword := randAlphaNum 20 -}}
{{- $dbPassword := default (randAlphaNum 20) .Values.dbPassword -}}
{{- $bapiSqlName := include "call-nested" (list . "bapi-db" "bapi-db.fullname") -}}
{{- $bapiSqlServer := printf "%s.%s,%d" $bapiSqlName .Release.Namespace ( $bapiDbValues.service.port | int) -}}

{{- $azureblobAccountName:= "devstoreaccount1" -}}
{{- $azureblobAccountKey:= "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==" -}}
{{- $azureblobPort:= .Values.azurite.service.blobPort | int }}
{{- $azureblobQueuePort:= .Values.azurite.service.queuePort | int }}
{{- $azureblobTablePort:= .Values.azurite.service.tablePort | int }}
{{- $azureblobName := include "call-nested" (list . "azurite" "azurite.fullname") -}}
{{- $azureblobUrl:=  printf "http://%s.%s" $azureblobName .Release.Namespace }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ template "local-env.fullname" . }}
  labels:     
    {{- include "local-env.labels" . | nindent 4 }}
type: Opaque
data:  
  sa-password: {{ $saPassword | b64enc | quote }}  
  db-password: {{ $dbPassword | b64enc | quote }}
  azure-blob-connection-string: {{ printf "AccountName=%s;AccountKey=%s;DefaultEndpointsProtocol=http;BlobEndpoint=%s:%d/%s;QueueEndpoint=%s:%d/%s;TableEndpoint=%s:%d/%s;" $azureblobAccountName $azureblobAccountKey $azureblobUrl $azureblobPort $azureblobAccountName $azureblobUrl $azureblobQueuePort $azureblobAccountName $azureblobUrl $azureblobTablePort $azureblobAccountName | b64enc | quote }}
  bapi-db-connection-string: {{ printf "Server=%s;Initial Catalog=%s;Persist Security Info=False;User Id=%s;Password=%s" $bapiSqlServer $bapiDbValues.dbName $bapiDbValues.dbUser $dbPassword | b64enc | quote }}
