pool:
  name: GP IT Futures AKS Build Agents
steps:

- task: CopyFiles@2
  displayName: 'Copy Files to: Azure'
  inputs:
    SourceFolder: 'Azure'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)\Azure'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Files to: Kubernetes'
  inputs:
    SourceFolder: 'Kubernetes'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)\Kubernetes'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Files to: Utility Services'
  inputs:
    SourceFolder: 'UtilityServices'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)\utilityservices'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Azure'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Azure'
    ArtifactName: Azure

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Kubernetes'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Kubernetes'
    ArtifactName: Kubernetes

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Utility Services'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\utilityservices'
    ArtifactName: UtilityServices
