pool:
  name: GP IT Futures AKS Build Agents
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: Azure'
  inputs:
    SourceFolder: Azure
    TargetFolder: '$(build.artifactstagingdirectory)\Azure'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Files to: Kubernetes'
  inputs:
    SourceFolder: Kubernetes
    TargetFolder: '$(build.artifactstagingdirectory)\Kubernetes'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Files to: Utility Services'
  inputs:
    SourceFolder: 'UtilityServices'
    TargetFolder: '$(build.artifactstagingdirectory)\utilityservices'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Azure'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Azure'
    ArtifactName: Azure

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Kubernetes'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Kubernetes'
    ArtifactName: Kubernetes

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Utility Services'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\utilityservices'
    ArtifactName: UtilityServices

- task: DockerInstaller@0
  displayName: 'Install Docker'
  inputs:
    dockerVersion: '18.06.1-ce'

- task: DockerCompose@0
  displayName: 'Build: (VSTS Build)'
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturesdevacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-dev-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesdevacr"}'
    dockerComposeFile: 'Kubernetes/AzureBuildAgent/docker-compose.yml'
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)'
    includeSourceTags: true
  enabled: false

- task: DockerCompose@0
  displayName: 'Push: (VSTS Build)'
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturesdevacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-dev-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesdevacr"}'
    dockerComposeFile: 'WIP/docker-compose.yml'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'
    includeSourceTags: true
    includeLatestTag: true
  enabled: false