apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-marketingpage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-marketingpage
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-marketingpage
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-marketingpage
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/marketingpage
        command: ["/bin/sh"]
        args: ["-c", "npm run start"]
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: API_HOST
        - name: BLOBSTORE_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: BLOBSTORE_HOST
        - name: DOCUMENT_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: DOCUMENT_HOST
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-dapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-dapi
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-dapi
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-dapi
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/document-dapi
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: AZUREBLOBSTORAGE__CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
                name: devpipelinevariables
                key: AZUREBLOBSTORAGE__CONNECTIONSTRING
        - name: AZUREBLOBSTORAGE__CONTAINERNAME
          valueFrom:
            secretKeyRef:
                name: devpipelinevariables
                key: AZUREBLOBSTORAGE__CONTAINERNAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-api
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-api
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-api
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/api
        ports:
        - containerPort: 5100
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: ConnectionStrings__BuyingCatalogue
          valueFrom:
              secretKeyRef:
                name: devpipelinevariables
                key: ConnectionStrings__BuyingCatalogue
        - name: APICLIENTSETTINGS__DOCUMENTAPI__BASEURL
          valueFrom:
            secretKeyRef:
                name: devpipelinevariables
                key: APICLIENTSETTINGS__DOCUMENTAPI__BASEURL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-nginx
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-nginx
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-nginx
        image: gpitfuturespprodacr.azurecr.io/nhsd/buying-catalogue/nginx/mp
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: marketingpage
spec:
  ports:
  - port: 3002
  selector:
    app: gpitfutures-bc-app
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: gpitfutures-bc-app-nginx
---
apiVersion: v1
kind: Service
metadata:
 name: dapi
spec:
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
  selector:
    app: gpitfutures-bc-app
---
apiVersion: v1
kind: Service
metadata:
 name: api
spec:
  ports:
  - port: 5100
    targetPort: 80
    protocol: TCP
  selector:
    app: gpitfutures-bc-app
