apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bapi-db.fullname" . }}
  labels:     
    {{- include "bapi-db.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.saPassword }}
  sa-password: {{ default "" .Values.saPassword | b64enc | quote }}
  {{- else }}
  sa-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.dbPassword }}
  db-password: {{ default "" .Values.dbPassword | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  