apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-dapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-dapi
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-dapi
    spec:
      containers:
      - name: gpitfutures-bc-app-dapi
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/document-dapi
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 1
        env:
        - name: AZUREBLOBSTORAGE__CONNECTIONSTRING
          value: srt-azureblobstorageconnectionstring@azurekeyvault
        - name: AZUREBLOBSTORAGE__CONTAINERNAME
          value: srt-azureblobstoragecontainername@azurekeyvault
---
apiVersion: v1
kind: Service
metadata:
 name: dapi
spec:
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
  selector:
    app: gpitfutures-bc-app-dapi
