    metadata:
      labels:
        app: gpitfutures-bc-app-dapi
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-dapi
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/dapi
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:                                
        - name: ConnectionStrings__BuyingCatalogue
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: ConnectionStrings__BuyingCatalogue
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: buyingcatalogue-dev-mp
spec:
  ports:
  - port: 5120
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: gpitfutures-bc-app-dapi