apiVersion: v1
kind: Secret
metadata:
  name: bcspsecret
type: Opaque
stringData:
  SHAREPOINT_CLIENT_ID: "b99d119f-4e8d-40bc-815f-64baab8f03a4"
  SHAREPOINT_CLIENT_SECRET: " 1H9Ooyz1AgYw7zwn14zlexzS1kLcwuusW/A9HO7ZGCg="
  SHAREPOINT_LOGIN: "buying.catalogue@hscic365.onmicrosoft.com"
  SHAREPOINT_PASSWORD: "Dinocorn19"