apiVersion: v1
kind: Secret
metadata:
  name: testpipelinevariables
type: Opaque
stringData:
    API_HOST: "http://api:5100"
    APICLIENTSETTINGS__DOCUMENTAPI__BASEURL: "http://nhsd.buyingcatalogue.documents.api.wiremock:80"
    BLOBSTORE_HOST: "https://gpitfuturestestsa.blob.core.windows.net"
    ConnectionStrings__BuyingCatalogue: "Server=tcp:gpitfutures-test-sql-pri.database.windows.net,1433;Initial Catalog=gpitfutures-test-db;Persist Security Info=False;User ID=gpitfbcadmin;Password=azcq8urpmgywvxobjldL6ie2hksfnt7;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    DOCUMENT_HOST: "http://localhost:63600"