apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-publicbrowse
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-publicbrowse
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-publicbrowse
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-publicbrowse
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/publicbrowse
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:

          ## LOGGER_LEVEL options are info, warn, error, off
        - name: LOGGER_LEVEL #
          value: srt.logger-level@azurekeyvault

          ## Boolean to indicate if we show the login/logout component
        - name: LOGIN_ENABLED
          value: "true"

          ##Boolean to indicate if we show the capabilities selector page
        - name: USE_CAPABILITIES_SELECTOR
          value: "true"

          ##Boolean to indicate if we show the COVID-19 feature
        - name: SHOW_COVID19
          value: "true"

          ## Node Environment
        - name: NODE_ENV #
          value: srt-node-env@azurekeyvault

          ## The base uri the app is running on to pass to identity service for redirection
        - name: APP_BASE_URI #
          value: srt.app-base-url@azurekeyvault

          ## The base uri of identity service
        - name: OIDC_BASE_URI #
          value: srt.oidc-base-uri@azurekeyvault

          ## The client id to be sent to identity service
        - name: OIDC_CLIENT_ID #
          value: srt.oidc-client-id@azurekeyvault

          ## The secret need to decode JWT tokens
        - name: OIDC_CLIENT_SECRET #
          value: srt.oidc.client-secret@azurekeyvault

        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"

          ## BUYING_CATALOGUE_ADMIN_HOST
        - name: BUYING_CATALOGUE_ADMIN_HOST #
          value: srt.admin-host@azurekeyvault

          ##  Environment variable to allow front end services talk to bapi
        - name: API_HOST #
          value: srt.api-host@azurekeyvault

          ## URL for Azure Storage Account
        - name: BLOBSTORE_HOST
          value: srt.blobstore-host@azurekeyvault

          ## Environment variable to allow front end services talk to dapi
        - name: DOCUMENT_HOST
          value: srt.document-host@azurekeyvault

          ## The url in which redis is running
        - name: REDIS_URL
          value: srt.redis-url@azurekeyvault

          ## The port redis is runnin
        - name: REDIS_PORT
          value: srt.redis-port@azurekeyvault

          ## Boolean to indicate whether to connect to redis via TLS
        - name: REDIS_TLS
          value: srt.redis-tls@azurekeyvault

          ## The password to connect to redis
        - name: REDIS_PASS
          value: srt.redis-pass|@azurekeyvault
---
apiVersion: v1
kind: Service
metadata:
  name: publicbrowse
spec:
  ports:
  - port: 3000
  selector:
    app: gpitfutures-bc-app-publicbrowse
