apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-publicbrowse
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-publicbrowse
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-publicbrowse
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-publicbrowse
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/publicbrowse
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: LOGGER_LEVEL
          value: "info"
        - name: LOGIN_ENABLED
          value: "true"
        - name: USE_CAPABILITIES_SELECTOR
          value: "true"
        - name: SHOW_COVID19
          value: "true"
        - name: NODE_ENV
          value: "production"
        - name: APP_BASE_URI
          value: "https://buyingcataloguedev.uksouth.cloudapp.azure.com"
        - name: OIDC_BASE_URI
          value: "https://buyingcataloguedev.uksouth.cloudapp.azure.com/identity"
        - name: OIDC_CLIENT_ID
          value: "NodeClient"
        - name: OIDC_CLIENT_SECRET
          value: "SECRET"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: BUYING_CATALOGUE_ADMIN_HOST
          value: "/admin"
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: API_HOST
        - name: BLOBSTORE_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: BLOBSTORE_HOST
        - name: DOCUMENT_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: DOCUMENT_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: publicbrowse
spec:
  ports:
  - port: 3000
  selector:
    app: gpitfutures-bc-app-publicbrowse
