apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-publicbrowse
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-publicbrowse
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-publicbrowse
    spec:
      containers:
      - name: gpitfutures-bc-app-publicbrowse
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/publicbrowse
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:

          ## logger_level options are info, warn, error, off"
        - name: LOGGER_LEVEL
          value: srt-loggerlevel@azurekeyvault

          ## Boolean to indicate if we show the login/logout component
        - name: LOGIN_ENABLED
          value: "true"

          ## Boolean to indicate if we show the capabilities selector page
        - name: USE_CAPABILITIES_SELECTOR
          value: "true"

          ## Boolean to indicate if we show the COVID-19 feature
        - name: SHOW_COVID19
          value: "true"

          ## Node environment
        - name: NODE_ENV
          value: "development"

          ## The base uri the app is running on to pass to identity service for redirection
        - name: APP_BASE_URI
          value: srt-appbaseuri@azurekeyvault

          ## The base uri of identity service
        - name: OIDC_BASE_URI
          value: srt-oidcbaseuri@azurekeyvault

          ## The client id to be sent to identity service
        - name: OIDC_CLIENT_ID
          value: srt-oidcclientid@azurekeyvault

          ## The secret need to decode JWT tokens
        - name: OIDC_CLIENT_SECRET
          value: srt-oidcclientsecret@azurekeyvault

          ## Allow invalid self-signed ssl certificate
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"

          ## Admin Host
        - name: BUYING_CATALOGUE_ADMIN_HOST
          value: srt-buyingcatalogueadminhost@azurekeyvault

          ##  Environment variable to allow front end services talk to bapi
        - name: API_HOST
          value: srt-apihost@azurekeyvault

          ## URL for Azure Storage Account
        - name: BLOBSTORE_HOST
          value: srt-blobstorehost@azurekeyvault

          ## Environment variable to allow front end services talk to dapi
        - name: DOCUMENT_HOST
          value: srt-documenthost@azurekeyvault

          ## The Host in which redis is running
        - name: REDIS_URL
          value: srt-redishost@azurekeyvault

          ## The port redis is running
        - name: REDIS_PORT
          value: srt-redisport@azurekeyvault

          ## Boolean to indicate whether to connect to redis via TLS
        - name: REDIS_TLS
          value: srt-redistls@azurekeyvault

          ## The password to connect to redis
        - name: REDIS_PASS
          value: srt-redispass@azurekeyvault

          ## How long before the cookies stored in the session expire in ms
        - name: MAX_COOKIE_AGE
          value: srt-maxcookieage@azurekeyvault

          ## The secret needed for encoding and decoding the cookie
        - name: COOKIE_SECRET
          value: srt-cookiesecret@azurekeyvault

          ## OrderForm Host
        - name: ORDER_FORM_HOST
          value: srt-orderformhost@azurekeyvault
---
apiVersion: v1
kind: Service
metadata:
  name: publicbrowse
spec:
  ports:
  - port: 3000
  selector:
    app: gpitfutures-bc-app-publicbrowse
