apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-publicbrowse
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-publicbrowse
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-publicbrowse
    spec:
      imagePullSecrets:
      - name: prodpipelinevariables
      containers:
      - name: gpitfutures-bc-app-publicbrowse
        image: gpitfuturesprodacr.azurecr.io/nhsd/buying-catalogue/publicbrowse:1.24.1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOGGER_LEVEL
          value: "info"
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: API_HOST
        - name: BLOBSTORE_HOST
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: BLOBSTORE_HOST
        - name: DOCUMENT_HOST
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: DOCUMENT_HOST
        - name: LOGIN_ENABLED
          value: "false"
        - name: USE_CAPABILITIES_SELECTOR
          value: "true"
        - name: SHOW_COVID19
          value: "true"
        - name: SHOW_ORDER_FORM
          value: "false"
        - name: BASE_URL
          value: ""
        - name: APP_BASE_URI
          value: "https://buyingcatalogue.digital.nhs.uk"
        - name: BUYING_CATALOGUE_ADMIN_HOST
          value: "/admin"
        - name: OIDC_BASE_URI
          value: "https://buyingcatalogue.digital.nhs.uk/identity"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: OIDC_CLIENT_SECRET
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: COOKIE_SECRET
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: REDIS_HOST
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_TLS
          value: "true"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: REDIS_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: publicbrowse
spec:
  ports:
  - port: 3000
  selector:
    app: gpitfutures-bc-app-publicbrowse
