apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-publicbrowse
  namespace: buyingcatalogue-prod-pb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1   
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-publicbrowse
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-publicbrowse
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-publicbrowse
        image: gpitfuturesprodacr.azurecr.io/nhsd/buying-catalogue/publicbrowse
        command: ["/bin/sh"]
        args: ["-c", "npm run start"]
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:                                
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: API_HOST
        - name: BLOBSTORE_HOST
          valueFrom:
            secretKeyRef:
              name: prodpipelinevariables
              key: BLOBSTORE_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: publicbrowse
  namespace: buyingcatalogue-prod-pb
spec:
  ports:
  - port: 3000
  selector:
    app: gpitfutures-bc-app-publicbrowse