apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-publicbrowse
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-publicbrowse
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-publicbrowse
    spec:
      imagePullSecrets:
      - name: testpipelinevariables
      containers:
      - name: gpitfutures-bc-app-publicbrowse
        image: gpitfuturestestacr.azurecr.io/nhsd/buying-catalogue/publicbrowse
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: LOGGER_LEVEL
          value: "info"
        - name: LOGIN_ENABLED
          value: "true"
        - name: USE_CAPABILITIES_SELECTOR
          value: "true"
        - name: SHOW_COVID19
          value: "true"
        - name: NODE_ENV
          value: "production"
        - name: APP_BASE_URI
          value: "https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com"
        - name: OIDC_BASE_URI
          value: "https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/identity"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: OIDC_CLIENT_SECRET
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: BUYING_CATALOGUE_ADMIN_HOST
          value: "/admin"
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: API_HOST
        - name: BLOBSTORE_HOST
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: BLOBSTORE_HOST
        - name: DOCUMENT_HOST
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: DOCUMENT_HOST
        - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: devpipelinevariables
                key: REDIS_HOST
        - name: REDIS_PORT
          value: 6380
        - name: REDIS_TLS
          value: "true"
        - name: REDIS_PASS             
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: REDIS_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: publicbrowse
spec:
  ports:
  - port: 3000
  selector:
    app: gpitfutures-bc-app-publicbrowse
