apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-marketingpage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-marketingpage
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-marketingpage
    spec:
      containers:
      - name: gpitfutures-bc-app-marketingpage
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/marketingpage
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
          ## Environment variable to allow front end services talk to bapi
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: API_HOST

          ## URL for Azure Storage Account
        - name: BLOBSTORE_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: BLOBSTORE_HOST

          ## Environment variable to allow front end services talk to dapi
        - name: DOCUMENT_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: DOCUMENT_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: marketingpage
spec:
  ports:
  - port: 3002
  selector:
    app: gpitfutures-bc-app-marketingpage
