apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-marketingpage
  namespace: buyingcatalogue
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1   
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-marketingpage
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-marketingpage
    spec:
      imagePullSecrets:
      - name: regcred3
      containers:
      - name: gpitfutures-bc-beta-marketingpage
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/marketingpage:sdb
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:                                
        - name: API_HOST
          value: http://bapi.buyingcatalogue:5100
        - name: BLOBSTORE_HOST
          value: http://dapi.buyingcatalogue:5101
---
apiVersion: v1
kind: Service
metadata:
  name: marketingpage
  namespace: buyingcatalogue
spec:
  ports:
  - port: 3002
  selector:
    app: gpitfutures-bc-app-marketingpage
  type: LoadBalancer