apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-marketingpage
  namespace: buyingcatalogue-pprod-mp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1   
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-marketingpage
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-marketingpage
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-marketingpage
        image: gpitfuturespprodacr.azurecr.io/nhsd/buying-catalogue/marketingpage
        command: ["/bin/sh"]
        args: ["-c", "npm run start"]
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:                                
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: pprodpipelinevariables
              key: API_HOST
        - name: BLOBSTORE_HOST
          valueFrom:
            secretKeyRef:
              name: pprodpipelinevariables
              key: BLOBSTORE_HOST   
---
apiVersion: v1
kind: Service
metadata:
  name: marketingpage
  namespace: buyingcatalogue-pprod-mp
spec:
  ports:
  - port: 3002
  selector:
    app: gpitfutures-bc-app-marketingpage