apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azurite.fullname" . }}
  labels:
    {{- include "azurite.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "azurite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "azurite.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "azurite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- include "image.properties" . | nindent 10 }}
          ports:
            - name: blob-port
              containerPort: {{ .Values.service.blobPort | default 10000 }}
              protocol: TCP
            - name: queue-port
              containerPort: {{ .Values.service.queuePort | default 10001 }}
              protocol: TCP
            - name: table-port
              containerPort: {{ .Values.service.tablePort | default 10002 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
