{{- $name := include "bapi-db.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bapi-db.fullname" . }}
  labels:
    {{- include "bapi-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bapi-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bapi-db.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bapi-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- include "image.properties" . | nindent 10 }}
          ports:
            - name: mssql
              containerPort: {{ .Values.service.port }}
          # livenessProbe:
          #    tcpSocket:
          #      port: mssql
          #    initialDelaySeconds: {{ .Values.livenessprobe.initialDelaySeconds }}
          #    periodSeconds: {{ .Values.livenessprobe.periodSeconds }}
          # readinessProbe:
          #    tcpSocket:
          #      port: mssql
          #    initialDelaySeconds: {{ .Values.readinessprobe.initialDelaySeconds }}
          #    periodSeconds: {{ .Values.readinessprobe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.saPasswordSecret.name }}
                  key: {{ .Values.saPasswordSecret.key }}
            - name: ACCEPT_EULA
              value: "Y"      
            - name: MSSQL_PID
              value: Developer  
            - name: DB_NAME
              value: {{ .Values.dbName | quote }}
            - name: DB_USER
              value: {{ .Values.dbUser | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbPasswordSecret.name }}
                  key: {{ .Values.dbPasswordSecret.key }}
            {{- if .Values.env.values }}
            {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.env.configmap }}
            {{- range .Values.env.configmap }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $cfgname }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
            {{- if .Values.env.secrets }}
            {{- range .Values.env.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:            
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}            
            {{- end }}
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
