apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-organisations
  namespace: buyingcatalogue
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-organisations  
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-organisations
    spec:
      imagePullSecrets:
      - name: regcredlocal
      containers:
      - name: gpitfutures-bc-beta-organisations
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/organisations-api
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        env:                                
        - name: CONNECTIONSTRINGS__CATALOGUEUSERS
          value: Server=isapi-mssql-deployment.buyingcatalogue,1451;Initial Catalog=CatalogueUsers;MultipleActiveResultSets=True;User Id=NHSD;Password=DisruptTheMarket1!
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: AUTHORITY
          value: http://host.docker.internal:5102
---
apiVersion: v1
kind: Service
metadata:
  name: organisations
  namespace: buyingcatalogue
spec:
  ports:
  - port: 5103
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: gpitfutures-bc-app-organisations
  type: LoadBalancer
