apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-publicbrowse
  namespace: buyingcatalogue
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1   
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-publicbrowse
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-publicbrowse
    spec:
      imagePullSecrets:
      - name: regcredlocal
      containers:
      - name: gpitfutures-bc-beta-publicbrowse
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/publicbrowse
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 250m
          limits:
            cpu: 1000m
            memory: 300Mi
        env:                                
        - name: API_HOST
          value: http://bapi.buyingcatalogue:5100
        - name: DOCUMENT_HOST
          value: http://dapi.buyingcatalogue:5101
        - name: APP_BASE_URI
          value: http://localhost:3000
        - name: OIDC_BASE_URI
          value: http://host.docker.internal:5102
        - name: OIDC_CLIENT_ID
          value: 'SampleClient'
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-client-secret
              key: OIDC_CLIENT_SECRET
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: publicbrowse
  namespace: buyingcatalogue
spec:
  ports:
  - port: 3000
  selector:
    app: gpitfutures-bc-app-publicbrowse
  type: LoadBalancer