apiVersion: v1
kind: Service
metadata:
  name: isapi-mssql-deployment
  namespace: buyingcatalogue
spec:
  ports:
  - port: 1451
    targetPort: 1433
    protocol: TCP    
  selector:
    app: isapi-mssql
  type: LoadBalancer #ClusterIP

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: isapi-mssql-deployment
  namespace: buyingcatalogue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: isapi-mssql
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: regcredlocal
      containers:
      - name: isapi-mssql        
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/identity-api-user-db 
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "MyTestPassword123!"
        - name: MSSQL_PID
          value: "Express"
        - name: DB_NAME
          value: "CatalogueUsers"
        - name: NHSD_PASSWORD
          value: "DisruptTheMarket1!"
        - name: INSERT_TEST_DATA
          value: "True"
        - name: CREATE_EA_USER 
          value: "True"
        - name: EA_USER_FIRST_NAME
          value: "Agency"
        - name: EA_USER_LAST_NAME
          value: "User"
        - name: EA_USER_EMAIL
          value: user@agency.com
        - name: EA_USER_PASSWORD_HASH
          value: "AQAAAAEAACcQAAAAEEOFkNNrFpKmDC2TBv2CP/dzxfnjdXk97RoqRlunE/CGs2tmFcewKZj4M/fITiP2tg=="
        - name: EA_USER_PHONE
          value: "01234567890"
