apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-azurite
  namespace: buyingcatalogue
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-deployment-azurite 
  template:
    metadata:
      labels:
        app: gpitfutures-bc-deployment-azurite
    spec: 
      imagePullSecrets:
        - name: regcredlocal     
      containers:
      - name: gpitfutures-bc-deployment-azurite
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
        - containerPort: 10000
        - containerPort: 10001
        - containerPort: 10002
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: buyingcatalogue
spec:
  ports:
  - port: 10000
    targetPort: 10000
    protocol: TCP 
    name: blob   
  - port: 10001
    targetPort: 10001
    protocol: TCP
    name: queue
  - port: 10002
    targetPort: 10002
    protocol: TCP
    name: table
  selector:
    app: gpitfutures-bc-deployment-azurite
  type: LoadBalancer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: file-loader
  namespace: buyingcatalogue
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcredlocal
      containers:
      - name: file-uploader        
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/file-uploader
        env:                                
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://azurite.buyingcatalogue:10000/devstoreaccount1;QueueEndpoint=http://azurite.buyingcatalogue:10001/devstoreaccount1;TableEndpoint=http://azurite.buyingcatalogue:10002/devstoreaccount1;
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 500Mi
      restartPolicy: OnFailure



      