apiVersion: v1
kind: Service
metadata:
  name: {{ include "oapi.fullname" . }}
  labels:
    {{- include "oapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oapi.selectorLabels" . | nindent 4 }}
