apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-adminpage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-adminpage
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-adminpage
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-adminpage
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/admin
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: API_HOST
        - name: BLOBSTORE_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: BLOBSTORE_HOST
        - name: DOCUMENT_HOST
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: DOCUMENT_HOST
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: COOKIE_SECRET
        - name: oidcClientSecret
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: oidcClientSecret
        - name: LOGGER_LEVEL
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: LOGGER_LEVEL
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
  - port: 3005
  selector:
    app: gpitfutures-bc-app-adminpage
