apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-adminpage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-adminpage
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-adminpage
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-adminpage
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/admin
        ports:
        - containerPort: 3005
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /admin/health/live
            port: 3005
        readinessProbe:
          httpGet:
            path: /admin/health/live
            port: 3005
        env:
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: COOKIE_SECRET
        - name: LOGGER_LEVEL
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: LOGGER_LEVEL
        - name: APP_BASE_URI
          value: "https://buyingcataloguedev.uksouth.cloudapp.azure.com"
        - name: BASE_URL
          value: "/admin"
        - name: OIDC_BASE_URI
          value: "https://buyingcataloguedev.uksouth.cloudapp.azure.com/identity"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: OIDC_CLIENT_SECRET
        - name: IDENTITY_SERVER
          value: "https://buyingcataloguedev.uksouth.cloudapp.azure.com/identity"
        - name: ORGANISATION_API_URL
          value: "http://oapi:5103"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: REDIS_HOST
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_TLS
          value: "true"
        - name: REDIS_PASS             
          valueFrom:
            secretKeyRef:
              name: devpipelinevariables
              key: REDIS_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
  - port: 3005
  selector:
    app: gpitfutures-bc-app-adminpage
