apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-adminpage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-adminpage
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-adminpage
    spec:
      containers:
      - name: gpitfutures-bc-app-adminpage
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/admin
        ports:
        - containerPort: 3005
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /admin/health/live
            port: 3005
        readinessProbe:
          httpGet:
            path: /admin/health/live
            port: 3005
        env:
          ## Base URL
        - name: BASE_URL
          value: "/admin"

          ## The secret needed for encoding and decoding the cookie
        - name: COOKIE_SECRET
          value: srt-cookiesecret@azurekeyvault

          ## logger_level options are info, warn, error, off
        - name: LOGGER_LEVEL
          value: info

          ## The base uri the app is running on to pass to identity service for redirection
        - name: APP_BASE_URI
          value: "https://buyingcataloguedev.uksouth.cloudapp.azure.com"

          ## The base uri of identity service
        - name: OIDC_BASE_URI
          value: srt-oidcbaseuri@azurekeyvault

          ## The client id to be sent to identity service
        - name: OIDC_CLIENT_ID
          value: srt-oidcclientid@azurekeyvault

          ## The secret need to decode JWT tokens
        - name: OIDC_CLIENT_SECRET
          value: srt-oidcclientsecret@azurekeyvault

          ## identity server
        - name: IDENTITY_SERVER
          value: "https://buyingcataloguedev.uksouth.cloudapp.azure.com/identity"

          ## organization api url
        - name: ORGANISATION_API_URL
          value: "http://oapi:5103"

          ## Allow invalid self-signed ssl certificate
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"

          ## The Host in which redis is running
        - name: REDIS_URL
          value: srt-redishost@azurekeyvault

          ## The port redis is running
        - name: REDIS_PORT
          value: srt-redisport@azurekeyvault

          ## Boolean to indicate whether to connect to redis via TLS
        - name: REDIS_TLS
          value: srt-redistls@azurekeyvault

          ## The password to connect to redis
        - name: REDIS_PASS
          value: srt-redispass@azurekeyvault

          ## public browse base url"
        - name: PUBLIC_BROWSE_BASE_URL
          value: "https://buyingcataloguedev.uksouth.cloudapp.azure.com"
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
  - port: 3005
  selector:
    app: gpitfutures-bc-app-adminpage
