apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-commander.fullname" . }}
  labels:
    {{- include "redis-commander.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-commander.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis-commander.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redis-commander.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- include "image.properties" . | nindent 10 }}
          ports:
            - name: port
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:  
            - name: K8S_SIGTERM
              value: "1"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.redisHost.name | quote }}
                  key: {{ .Values.redisHost.key | quote }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
