apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-commander.fullname" . }}
  labels:
    {{- include "redis-commander.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: port
    
  selector:
    {{- include "redis-commander.selectorLabels" . | nindent 4 }}
