{{- $dapiUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "dapi" "dapi.fullname")) .Release.Namespace) .Values.dapi.disabledUrl .Values.dapi.enabled -}}
{{- $bapiUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "bapi" "bapi.fullname")) .Release.Namespace) .Values.bapi.disabledUrl .Values.bapi.enabled -}}
{{- $isapiUrl:= ternary .Values.dockerInternalLocalhost .Values.isapi.disabledUrl .Values.isapi.enabled -}}
{{- $areAllFEComponentsEnabled:= and .Values.mp.enabled .Values.pb.enabled .Values.admin.enabled -}}
{{- $isapiIssuerUrl:= ternary .Values.dockerInternalLocalhost .Values.isapi.feDisabledIssuerUrl $areAllFEComponentsEnabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "buyingcatalogue.fullname" . }}
  labels:     
    {{- include "buyingcatalogue.labels" . | nindent 4 }}
data:
  dapi-url: {{ printf "http://%s:%d" $dapiUrl (.Values.dapi.service.port | int ) }}
  bapi-url: {{ printf "http://%s:%d" $bapiUrl (.Values.bapi.service.port | int ) }}
  isapi-url: "http://51.132.48.118/"
  issuer-url: "http://51.132.48.118/"
