{{- $dapiUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "dapi" "dapi.fullname")) .Release.Namespace) .Values.dapi.disabledUrl .Values.dapi.enabled -}}
{{- $bapiUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "bapi" "bapi.fullname")) .Release.Namespace) .Values.bapi.disabledUrl .Values.bapi.enabled -}}
{{- $isapiUrl:= ternary "host.docker.internal" .Values.isapi.disabledUrl .Values.isapi.enabled -}}
{{- $isapiIssuerUrl:= ternary "host.docker.internal" .Values.isapi.feDisabledIssuerUrl .Values.pb.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "buyingcatalogue.fullname" . }}
  labels:     
    {{- include "buyingcatalogue.labels" . | nindent 4 }}
data:
  dapi-url: {{ printf "http://%s:%d" $dapiUrl (.Values.dapi.service.port | int ) }}
  bapi-url: {{ printf "http://%s:%d" $bapiUrl (.Values.bapi.service.port | int ) }}
  isapi-url: {{ printf "http://%s:%d" $isapiUrl (.Values.isapi.service.port | int ) }}
  issuer-url: {{ printf "http://%s:%d" $isapiIssuerUrl (.Values.isapi.service.port | int ) }}