{{- $name := include "email.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "email.fullname" . }}
  labels:
    {{- include "email.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}  
  selector:
    matchLabels:
      {{- include "email.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "email.selectorLabels" . | nindent 8 }}
    spec:    
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "email.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}          
          {{- include "image.properties" . | nindent 10 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: smtps
              containerPort: 587
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
         
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
