apiVersion: v1
kind: Service
metadata:
  name: {{ include "email.fullname" . }}
  labels:
    {{- include "email.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.service.ports }}  
    - port: {{ .http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .smtps }}
      targetPort: smtps
      protocol: TCP
      name: smtps
    {{- end }}
  selector:
    {{- include "email.selectorLabels" . | nindent 4 }}
