apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-isapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-isapi
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-isapi
    spec:
      containers:
      - name: gpitfutures-bc-app-isapi
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/identity-isapi
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        livenessProbe:
          httpGet:
            path: /identity/health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /identity/health/ready
            port: 80
        env:
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: CONNECTIONSTRINGS__CATALOGUEUSERS
          value: srt-connectionstringcatalogueusers@azurekeyvault
        - name: ISSUERURL
          value: https://buyingcataloguedev.uksouth.cloudapp.azure.com/identity/
        - name: CLIENTS__0__CLIENTID
          value: srt-clients0clientid@azurekeyvault
        - name: CLIENTS__0__SECRET
          value: srt-clients0secret@azurekeyvault
        - name: CLIENTS__0__CLIENTNAME
          value: srt-clients0clientname@azurekeyvault
        - name: CLIENTS__0__REQUIRECLIENTSECRET
          value: "true"
        - name: CLIENTS__0__REDIRECTURLS__0
          value: https://buyingcataloguedev.uksouth.cloudapp.azure.com/oauth/callback
        - name: CLIENTS__0__REDIRECTURLS__1
          value: https://buyingcataloguedev.uksouth.cloudapp.azure.com/admin/oauth/callback
        - name: CLIENTS__0__POSTLOGOUTREDIRECTURLS__0
          value: https://buyingcataloguedev.uksouth.cloudapp.azure.com/signout-callback-oidc
        - name: CLIENTS__0__POSTLOGOUTREDIRECTURLS__1
          value: https://buyingcataloguedev.uksouth.cloudapp.azure.com/admin/signout-callback-oidc
        - name: SMTPSERVER__HOST
          value: srt-smtpserverhost@azurekeyvault
        - name: SMTPSERVER__PORT
          value: "587"
        - name: ALLOWINVALIDCERTIFICATE
          value: "true"
        - name: DATAPROTECTION__APPLICATIONNAME
          value: "ISAPI Development"
        - name: PUBLICBROWSE__BASEADDRESS
          value: https://buyingcataloguedev.uksouth.cloudapp.azure.com
        - name: PUBLICBROWSE__LOGINPATH
          value: /re-login
---
apiVersion: v1
kind: Service
metadata:
 name: isapi
spec:
  ports:
  - port: 8070
    targetPort: 80
    protocol: TCP
  selector:
    app: gpitfutures-bc-app-isapi
