apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-isapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-isapi
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-isapi
    spec:
      imagePullSecrets:
      - name: testpipelinevariables
      containers:
      - name: gpitfutures-bc-app-isapi
        image: gpitfuturestestacr.azurecr.io/nhsd/buying-catalogue/identity-isapi
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        livenessProbe:
          httpGet:
            path: /identity/health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /identity/health/ready
            port: 80
        env:
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: CONNECTIONSTRINGS__CATALOGUEUSERS
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: ConnectionStrings__CatalogueUsers
        - name: ISSUERURL
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/identity/
        - name: CLIENTS__0__CLIENTID
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: CLIENTS__0__CLIENTID
        - name: CLIENTS__0__SECRET
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: CLIENTS__0__SECRET
        - name: CLIENTS__0__CLIENTNAME
          value: "Node Client"
        - name: CLIENTS__0__REQUIRECLIENTSECRET
          value: "true"
        - name: CLIENTS__0__REDIRECTURLS__0
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/oauth/callback
        - name: CLIENTS__0__REDIRECTURLS__1
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/admin/oauth/callback
        - name: CLIENTS__0__REDIRECTURLS__2
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/order/oauth/callback
        - name: CLIENTS__0__POSTLOGOUTREDIRECTURLS__0
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/signout-callback-oidc
        - name: CLIENTS__0__POSTLOGOUTREDIRECTURLS__1
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/admin/signout-callback-oidc
        - name: CLIENTS__0__POSTLOGOUTREDIRECTURLS__2
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/order/signout-callback-oidc
        - name: CLIENTS__0__ALLOWEDSCOPES__0
          value: openid
        - name: CLIENTS__0__ALLOWEDSCOPES__1
          value: email
        - name: CLIENTS__0__ALLOWEDSCOPES__2
          value: profile
        - name: CLIENTS__0__ALLOWEDSCOPES__3
          value: Organisation
        - name: CLIENTS__0__ALLOWEDSCOPES__4
          value: Ordering
        - name: SMTPSERVER__HOST
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: SMTPSERVER__HOST
        - name: SMTPSERVER__PORT
          value: "587"
        - name: SMTPSERVER__EMAILSUBJECTPREFIX
          value: "test"
        - name: ALLOWINVALIDCERTIFICATE
          value: "true"
        - name: DATAPROTECTION__APPLICATIONNAME
          value: "ISAPI Test"
        - name: PUBLICBROWSE__BASEADDRESS
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com
        - name: PUBLICBROWSE__LOGINPATH
          value: /re-login
        - name: PUBLICBROWSE__LOGOUTPATH
          value: "/logout-callback"
---
apiVersion: v1
kind: Service
metadata:
 name: isapi
spec:
  ports:
  - port: 5102
    targetPort: 80
    protocol: TCP
  selector:
    app: gpitfutures-bc-app-isapi
