apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-oapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-oapi
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-oapi
    spec:
      imagePullSecrets:
      - name: testpipelinevariables
      containers:
      - name: gpitfutures-bc-app-oapi
        image: gpitfuturestestacr.azurecr.io/nhsd/buying-catalogue/organisations-api
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        env:
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: CONNECTIONSTRINGS__CATALOGUEUSERS
          valueFrom:
            secretKeyRef:
              name: testpipelinevariables
              key: ConnectionStrings__CatalogueUsers
        - name: AUTHORITY
          value: https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com/identity/
        - name: ALLOWINVALIDCERTIFICATE
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
 name: oapi
spec:
  ports:
  - port: 5103
    targetPort: 80
    protocol: TCP
  selector:
    app: gpitfutures-bc-app-oapi
